id: IC80638E3
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T13:13:34+00:00'
last_modified: '2022-06-07T12:22:08.367400+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC52
  title: བྱམས་ཆོས་སྡེ་ལྔ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '7230':
      image_group_id: I2PD18926
      title: Volume 1 of byams chos sde lnga/
      total_pages: 216
      order: 1
      base_file: 7230.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
