id: P000577
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1AC52
  title: བྱམས་ཆོས་སྡེ་ལྔ།
  author: ''
  volumes:
    df43596de78c41a887f5946fe1d55773:
      image_group_id: I2PD18926
      title: Volume 1 of byams chos sde lnga/
      volume_number: 1
      total_pages: 216
      base_file: v001.txt
