id: opecha:P000577
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC52
  title: བྱམས་ཆོས་སྡེ་ལྔ།
  volume:
    df43596de78c41a887f5946fe1d55773:
      image_group_id: I2PD18926
      title: Volume 1 of byams chos sde lnga/
      volume_number: 1
      total_pages: 216
  author: ''
ebook_metadata:
  title: བྱམས་ཆོས་སྡེ་ལྔ།
  author: ''
  sku: P000577
  cover: cover.jpg
  layers:
  - pagination
